# Research project based on the paper "Welfare, the earned income tax credit, and the labor supply of single mothers." by Bruce D. Meyer and Dan T. Rosenbaum

##Summary
In their paper "Welfare, the earned income tax credit, and the labor supply of single mothers." Bruce D. Meyer and Dan T. Rosenbaum (2001) state that tax and welfare reforms between 1984 and 1996 increased labor supply of single mothers by 6-9 % compared to childless single women.
 
